version: "3.3"

volumes:
  mongodb_data:
  mongodb_config:

services:
  mongodb:
    image: mongo:5.0.4-focal
    env_file: mongo.env
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./data:/data/input
    ports:
      - "27017:27017"
    restart: always
